"""Host-testable runtime contracts for Phase 1 asynchronous inference."""

from .broker import (
    BoundedTaskBroker,
    BrokerSnapshot,
    BrokerState,
    BrokerStateError,
    CancellationResult,
    ClaimedTask,
    ClaimResult,
    CompletionResult,
    ConsumptionResult,
    ShutdownResult,
    StateAdvanceResult,
    SubmissionResult,
    TerminalTransition,
)
from .events import (
    EventScalar,
    EventStatus,
    NullEventSink,
    RuntimeEvent,
    RuntimeEventSink,
)
from .executor import (
    ExecutorShutdownReport,
    ObservableExecutor,
    SimulatedAdapter,
    WorkloadAdapter,
)
from .model import (
    CancellationReport,
    CancellationToken,
    ExecutionOutcome,
    FinalDisposition,
    PayloadRef,
    ResultEnvelope,
    StateToken,
    TaskEnvelope,
    TaskKind,
    TaskLocation,
)
from .policies import LaneConfig, OverflowPolicy
from .probe import (
    PeriodicProbe,
    ProbeStopReport,
    ProbeTick,
    build_probe_tick,
    select_release,
)

__all__ = [
    "BoundedTaskBroker",
    "BrokerSnapshot",
    "BrokerState",
    "BrokerStateError",
    "CancellationReport",
    "CancellationResult",
    "CancellationToken",
    "ClaimedTask",
    "ClaimResult",
    "CompletionResult",
    "ConsumptionResult",
    "EventScalar",
    "EventStatus",
    "ExecutionOutcome",
    "ExecutorShutdownReport",
    "FinalDisposition",
    "LaneConfig",
    "NullEventSink",
    "ObservableExecutor",
    "OverflowPolicy",
    "PayloadRef",
    "PeriodicProbe",
    "ProbeStopReport",
    "ProbeTick",
    "ResultEnvelope",
    "RuntimeEvent",
    "RuntimeEventSink",
    "ShutdownResult",
    "StateAdvanceResult",
    "StateToken",
    "SimulatedAdapter",
    "SubmissionResult",
    "TaskEnvelope",
    "TaskKind",
    "TaskLocation",
    "TerminalTransition",
    "WorkloadAdapter",
    "build_probe_tick",
    "select_release",
]
